# Generated by Django 4.2.4 on 2023-08-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DEVICE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=128, verbose_name='设备名称')),
                ('device_status', models.BooleanField(verbose_name='设备状态')),
            ],
        ),
    ]
